CREATE TABLE SOCIAL_MEDIA (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	USER_MESSAGE VARCHAR(140),
	SHOW VARCHAR(100),
	USER_NICK VARCHAR(40),
	POSITIVE VARCHAR(100),
	NEGATIVE VARCHAR(100),
	NEUTRAL VARCHAR(100)
);