CREATE DATABASE streaming;
USE streaming;

-- criando tabela de tweets
CREATE TABLE TWEET (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USER_MESSAGE VARCHAR(140),
    CREATED_AT DATE,
	CONTENT VARCHAR(100),
	USER_NICK VARCHAR(40),
	POSITIVE VARCHAR(100),
	NEGATIVE VARCHAR(100),
	NEUTRAL VARCHAR(100)
);

-- criando tabaela para armazenar os resultados das impressões de uma análise
CREATE TABLE RATE_ANALYSIS (
	ID INT AUTO_INCREMENT(1,1) PRIMARY KEY,
	CONTENT VARCHAR(100),
	IMPRESSIONS VARCHAR(100),
	POSITIVE INT,
	NEGATIVE INT,
	NEUTRAL INT
);

-- criando tabela de títulos disponíveis para streaming na plataforma
CREATE TABLE CONTENT (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	CATEGORY VARCHAR(20) NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	DIRECTORS JSON,
	CAST_MEMBERS JSON,
	COUNTRY VARCHAR(50),
	DATE_ADDED DATE,
	RELEASE_YEAR YEAR NOT NULL,
	RATING VARCHAR(20),
	DURATION VARCHAR(30),
	LISTED_IN JSON NOT NULL,
	SHOW_DESC VARCHAR(50)
);